"""update user model fields

Revision ID: 18a5b790347b
Revises: 
Create Date: 2026-09-10 08:22:52.810903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a5b790347b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update users table columns directly
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])

    # 2. Re-link foreign keys on join tables without explicitly calling drop_constraint(None)
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_role_permissions_role_id', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_role_permissions_permission_id', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rule_facts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_rule_facts_fact_id', 'facts', ['fact_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_rule_facts_rule_id', 'rules', ['rule_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_expenses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_expenses_expense_id', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_user_expenses_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_histories', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_histories_history_id', 'histories', ['history_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_user_histories_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_incomes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_incomes_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_user_incomes_income_id', 'incomes', ['income_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_roles_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_user_roles_roles_id', 'roles', ['roles_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_roles_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_user_roles_roles_id', 'roles', ['roles_id'], ['id'])

    with op.batch_alter_table('user_incomes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_incomes_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_user_incomes_income_id', 'incomes', ['income_id'], ['id'])

    with op.batch_alter_table('user_histories', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_histories_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_user_histories_history_id', 'histories', ['history_id'], ['id'])

    with op.batch_alter_table('user_expenses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_expenses_expense_id', 'expenses', ['expense_id'], ['id'])
        batch_op.create_foreign_key('fk_user_expenses_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('rule_facts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_rule_facts_fact_id', 'facts', ['fact_id'], ['id'])
        batch_op.create_foreign_key('fk_rule_facts_rule_id', 'rules', ['rule_id'], ['id'])

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_role_permissions_permission_id', 'permissions', ['permission_id'], ['id'])
        batch_op.create_foreign_key('fk_role_permissions_role_id', 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('google_id')
        batch_op.drop_column('description')
        batch_op.drop_column('gender')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###