"""Add AIMessage model and link to AI session

Revision ID: 36df5eb0fed7
Revises: 18a5b790347b
Create Date: 2026-09-19 05:00:12.367778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36df5eb0fed7'
down_revision = '18a5b790347b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.Column('counts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_chats'))
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_id'], ['ai_chats.id'], name=op.f('fk_ai_messages_ai_id_ai_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('fact', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value_fact', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_conditions_rule_id_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_conditions'))
    )
    op.create_table('user_ai',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_id'], ['ai_chats.id'], name=op.f('fk_user_ai_ai_id_ai_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_ai_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ai_id', name=op.f('pk_user_ai'))
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_facts_tags'), ['tags'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('conclusion',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('advice',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_refresh_token'), ['refresh_token'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_refresh_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.alter_column('advice',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('conclusion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_facts_tags'), type_='unique')
        batch_op.alter_column('value',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('type')

    op.drop_table('user_ai')
    op.drop_table('rule_conditions')
    op.drop_table('ai_messages')
    op.drop_table('ai_chats')
    # ### end Alembic commands ###
