import re
import time
from datetime import datetime
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required, current_user
from app.models.ai_chat import AIChat, AIMessage
from app.models.history import History
from extension import db
from app.security.cookie import check_cookie_token
from app.services.llm_service import LLMService
from app.services.advisor_services import AdvisorServices
from app.security.limiter import limiter

bot_bp = Blueprint("bots", __name__, url_prefix="/bots")

@bot_bp.before_request
def check_token():
    check_cookie_token(current_user)

@bot_bp.route("/")
@login_required
def index():
    return render_template("bots/index.html")

@bot_bp.route("/chat", methods=["POST"])
@login_required
@limiter.limit("15 per minute; 60 per hour")
def chat():
    t_req_start = time.perf_counter()
    try:
        data = request.get_json(silent=True) or {}

        user_message = data.get("message", "").strip()
        chat_id = data.get("chat_id")

        if not user_message:
            return jsonify({"error": "Message cannot be empty"}), 400

        # Find existing chat belonging to the current user
        ai_chat = None

        if chat_id:
            ai_chat = (
                AIChat.query
                .filter(
                    AIChat.id == chat_id,
                    AIChat.users.any(id=current_user.id)
                )
                .first()
            )

        # If no valid chat was supplied, create a new one
        if not ai_chat:
            ai_chat = AIChat(
                descriptions="Financial Assistant",
                counts=0
            )

            ai_chat.users.append(current_user)

            db.session.add(ai_chat)
            db.session.flush()

        # Load previous messages from this conversation
        messages = (
            AIMessage.query
            .filter_by(ai_id=ai_chat.id)
            .order_by(AIMessage.created_at.asc())
            .all()
        )

        # 1. Detect language of the incoming message
        from training.llm_output_normalizer import (
            detect_language, classify_conversational_intent, normalize_llm_output,
            is_safety_violation, is_educational_query
        )
        lang = detect_language(user_message)

        # 2. Authoritative Source of Truth: Load existing financial profile scoped to current_user
        t_prof_start = time.perf_counter()
        existing_profile = AdvisorServices.get_user_financial_profile(current_user)
        t_prof_end = time.perf_counter()
        db_profile_loading_ms = round((t_prof_end - t_prof_start) * 1000.0, 2)

        # 3. Intent Classification
        t_intent_start = time.perf_counter()
        intent = classify_conversational_intent(
            user_message,
            has_profile=bool(existing_profile and existing_profile.get("monthly_income") is not None)
        )
        t_intent_end = time.perf_counter()
        intent_classification_ms = round((t_intent_end - t_intent_start) * 1000.0, 2)

        # =============================================================
        # ROUTING: Intent determines what actions to take (DB, Engine)
        # RESPONSE: Always generated by the trained local Financial Advisor AI
        # =============================================================

        consultant_advice = None
        consultant_engine_ms = 0.0
        ai_response = None

        if intent in ("greeting", "casual_conversation"):
            # Clean conversational response without calling ConsultantEngine or analyzing finances
            if intent == "greeting":
                ai_response = (
                    "សួស្តី! ខ្ញុំជាជំនួយការប្រឹក្សាហិរញ្ញវត្ថុ AI របស់អ្នក។ តើខ្ញុំអាចជួយអ្នកក្នុងការរៀបចំផែនការហិរញ្ញវត្ថុ ថវិកា ឬការសន្សំយ៉ាងដូចម្តេចដែរ?"
                    if lang == "km"
                    else "Hello! I am your Financial Advisor AI. How can I help you with your budgeting, savings, or financial planning today?"
                )
            else:
                ai_response = (
                    "សូមអរគុណ! ប្រសិនបើអ្នកមានសំណួរបន្ថែមអំពីហិរញ្ញវត្ថុ ខ្ញុំរីករាយនឹងជួយជានិច្ច។"
                    if lang == "km"
                    else "You're welcome! Let me know if you have any questions about your finances or savings goals."
                )

        elif intent == "income_fact_query" and existing_profile and existing_profile.get("monthly_income") is not None:
            inc_val = existing_profile["monthly_income"]
            ai_response = (
                f"ប្រាក់ចំណូលប្រចាំខែដែលបានកត់ត្រារបស់អ្នកគឺ ${inc_val:,.2f} ក្នុងមួយខែ។"
                if lang == "km"
                else f"Your recorded monthly take-home income is ${inc_val:,.2f}."
            )

        elif intent == "expense_fact_query" and existing_profile and existing_profile.get("monthly_expense") is not None:
            exp_val = existing_profile["monthly_expense"]
            ai_response = (
                f"ការចំណាយប្រចាំខែដែលបានកត់ត្រារបស់អ្នកគឺ ${exp_val:,.2f} ក្នុងមួយខែ។"
                if lang == "km"
                else f"Your recorded monthly living expenses are ${exp_val:,.2f}."
            )

        elif intent == "savings_capacity_query" and existing_profile and existing_profile.get("monthly_income") is not None and existing_profile.get("monthly_expense") is not None:
            inc_val = existing_profile["monthly_income"]
            exp_val = existing_profile["monthly_expense"]
            surplus_val = inc_val - exp_val
            ai_response = (
                f"ផ្អែកលើកម្រងព័ត៌មានរបស់អ្នក អ្នកអាចសន្សំបាន ${surplus_val:,.0f} ក្នុងមួយខែ (ចំណូល ${inc_val:,.0f} ដកចំណាយ ${exp_val:,.0f})។"
                if lang == "km"
                else f"Based on your financial profile, you can save ${surplus_val:,.0f} each month (${inc_val:,.0f} income minus ${exp_val:,.0f} expenses)."
            )

        elif intent == "expense_reduction_query" and existing_profile and existing_profile.get("monthly_expense") is not None:
            exp_val = existing_profile["monthly_expense"]
            ai_response = (
                f"ការចំណាយប្រចាំខែរបស់អ្នកបច្ចុប្បន្នគឺ ${exp_val:,.0f}។ ដើម្បីកាត់បន្ថយការចំណាយ សូមផ្តោតលើការកាត់បន្ថយការចំណាយមិនចាំបាច់ ដូចជាការដើរទិញឥវ៉ាន់ និងការជាវសេវាផ្សេងៗ។"
                if lang == "km"
                else f"Your current living expenses are ${exp_val:,.0f}/month. To reduce them, focus on cutting non-essential discretionary spending, dining out, and unused subscriptions."
            )

        elif intent == "goal_approach_query" and existing_profile:
            goal_v = existing_profile.get("goal_cost", 0.0) or 0.0
            inc_v = existing_profile.get("monthly_income", 0.0) or 0.0
            exp_v = existing_profile.get("monthly_expense", 0.0) or 0.0
            surplus_v = inc_v - exp_v
            months = round(goal_v / surplus_v) if surplus_v > 0 else 0
            ai_response = (
                f"ដើម្បីសម្រេចគោលដៅ ${goal_v:,.0f} របស់អ្នក ជាមួយនឹងប្រាក់សល់ ${surplus_v:,.0f} ក្នុងមួយខែ អ្នកអាចរៀបចំយុទ្ធសាស្ត្រសន្សំ រយៈពេលប្រហែល {months} ខែ។"
                if lang == "km"
                else f"To achieve your ${goal_v:,.0f} savings goal with your ${surplus_v:,.0f}/month surplus, follow a dedicated monthly allocation strategy over a projected timeline of ~{months} months."
            )

        elif intent in ("financial_plan_request", "savings_guidance") and existing_profile and existing_profile.get("monthly_income") is not None:
            # Run ConsultantEngine for authoritative assessment
            t_eng_start = time.perf_counter()
            result_dto, error_dto = AdvisorServices.consult(existing_profile, lang=lang)
            consultant_engine_ms = round((time.perf_counter() - t_eng_start) * 1000.0, 2)

            if result_dto and result_dto.get("success"):
                inc_val = existing_profile.get("monthly_income", 0.0) or 0.0
                exp_val = existing_profile.get("monthly_expense", 0.0) or 0.0
                surplus_val = inc_val - exp_val
                plan_advice = result_dto.get("advice", {}).get(lang) or result_dto.get("advice", {}).get("en", "")
                plan_explanation = result_dto.get("explanation", "")

                user_wants_english = bool(
                    re.search(
                        r"\b(in\s+english|english\s+please|as\s+english|respond\s+in\s+english|ជាភាសាអង់គ្លេស|សូមឆ្លើយជាភាសាអង់គ្លេស)\b",
                        user_message,
                        re.IGNORECASE
                    )
                )

                if intent == "financial_plan_request":
                    needs_target = round(inc_val * 0.50)
                    wants_target = round(inc_val * 0.30)
                    savings_target = round(inc_val * 0.20)

                    if lang == "km" and not user_wants_english:
                        has_english_letters = bool(re.search(r"[a-zA-Z]{3,}", plan_explanation or ""))
                        if not plan_explanation or has_english_letters:
                            plan_explanation = (
                                f"លំហូរសាច់ប្រាក់សុទ្ធប្រចាំខែរបស់អ្នកមានសញ្ញាវិជ្ជមាន +${surplus_val:,.0f} ដែលនៅសល់បន្ទាប់ពីការចំណាយចាំបាច់។ "
                                f"អ្នកប្រឹក្សាណែនាំឱ្យបែងចែកប្រាក់សល់នេះដើម្បីបង្កើតមូលនិធិសង្គ្រោះបន្ទាន់ និងសម្រេចគោលដៅហិរញ្ញវត្ថុរបស់អ្នក។"
                                if surplus_val > 0 else
                                f"ការចំណាយប្រចាំខែរបស់អ្នកបច្ចុប្បន្នលើសពីចំណូលចំនួន ${abs(surplus_val):,.0f} ក្នុងមួយខែ។"
                            )
                        ai_response = (
                            f"នេះជាផែនការហិរញ្ញវត្ថុផ្ទាល់ខ្លួនរបស់អ្នក ផ្អែកលើទិន្នន័យ (ចំណូល: ${inc_val:,.0f}/ខែ, ចំណាយ: ${exp_val:,.0f}/ខែ, សល់សុទ្ធ: +${surplus_val:,.0f}/ខែ)៖\n\n"
                            f"១. **ក្បួនបែងចែកថវិកា (ស្តង់ដារ 50/30/20)**:\n"
                            f"   * **តម្រូវការចាំបាច់ (៥០%)**: គោលដៅប្រហែល ${needs_target:,.0f}/ខែ (ចំណាយបច្ចុប្បន្ន: ${exp_val:,.0f}/ខែ)\n"
                            f"   * **ការចំណាយផ្ទាល់ខ្លួន (៣០%)**: គោលដៅប្រហែល ${wants_target:,.0f}/ខែ\n"
                            f"   * **ការសន្សំ (២០%)**: គោលដៅប្រហែល ${savings_target:,.0f}/ខែ សម្រាប់ប្រាក់បម្រុងបន្ទាន់\n\n"
                            f"២. **អនុសាសន៍ចម្បង**:\n"
                            f"   {plan_advice}\n\n"
                            f"៣. **ជំហានអនុវត្តជាក់ស្តែង**:\n"
                            f"   * បែងចែកប្រាក់សល់ ${surplus_val:,.0f}/ខែ ចូលទៅក្នុងមូលនិធិសង្គ្រោះបន្ទាន់។\n"
                            f"   * ពិនិត្យកាត់បន្ថយការចំណាយមិនចាំបាច់ ដើម្បីពង្រីកទំហំសន្សំប្រចាំខែ។\n\n"
                            f"**ការយល់ដឹងអំពីអនុសាសន៍របស់អ្នក**:\n{plan_explanation}"
                        )
                    else:
                        ai_response = (
                            f"Here is your personalized Financial Plan based on your verified monthly income of ${inc_val:,.0f} and expenses of ${exp_val:,.0f} (Net Surplus: +${surplus_val:,.0f}/mo):\n\n"
                            f"1. **Budget Framework (50/30/20 Benchmark)**:\n"
                            f"   * **Needs (50%)**: Target ~${needs_target:,.0f}/mo (current living expenses: ${exp_val:,.0f}/mo)\n"
                            f"   * **Wants (30%)**: Target ~${wants_target:,.0f}/mo for flexible personal spending\n"
                            f"   * **Savings (20%)**: Target ~${savings_target:,.0f}/mo toward emergency reserves\n\n"
                            f"2. **Primary Recommendation**:\n"
                            f"   {plan_advice}\n\n"
                            f"3. **Action Steps**:\n"
                            f"   * Allocate your verified surplus of ${surplus_val:,.0f}/mo toward your emergency buffer.\n"
                            f"   * Review discretionary spending to increase your monthly savings margin.\n\n"
                            f"**Understanding Your Recommendation**:\n{plan_explanation}"
                        )
                else:
                    if lang == "km" and not user_wants_english:
                        # Clean, fully Khmer response. Do not append English sections.
                        has_english_letters = bool(re.search(r"[a-zA-Z]{3,}", plan_explanation or ""))
                        if not plan_explanation or has_english_letters:
                            plan_explanation = (
                                f"លំហូរសាច់ប្រាក់សុទ្ធប្រចាំខែរបស់អ្នកមានសញ្ញាវិជ្ជមាន +${surplus_val:,.0f} ដែលនៅសល់បន្ទាប់ពីការចំណាយចាំបាច់។ "
                                f"អ្នកប្រឹក្សាណែនាំឱ្យបែងចែកប្រាក់សល់នេះដើម្បីបង្កើតមូលនិធិសង្គ្រោះបន្ទាន់ និងសម្រេចគោលដៅហិរញ្ញវត្ថុរបស់អ្នក។"
                                if surplus_val > 0 else
                                f"ការចំណាយប្រចាំខែរបស់អ្នកបច្ចុប្បន្នលើសពីចំណូលចំនួន ${abs(surplus_val):,.0f} ក្នុងមួយខែ។"
                            )
                        
                        ai_response = (
                            f"ផ្អែកលើទិន្នន័យហិរញ្ញវត្ថុរបស់អ្នក (ចំណូល: ${inc_val:,.0f}/ខែ, ចំណាយ: ${exp_val:,.0f}/ខែ, សល់សុទ្ធ: ${surplus_val:,.0f}/ខែ)៖\n\n"
                            f"{plan_advice}\n\n"
                            f"**ការយល់ដឹងអំពីអនុសាសន៍របស់អ្នក**:\n{plan_explanation}"
                        )
                    else:
                        ai_response = (
                            f"Based on your authoritative financial profile (Income: ${inc_val:,.0f}/mo, Expenses: ${exp_val:,.0f}/mo, Net Surplus: ${surplus_val:,.0f}/mo):\n\n"
                            f"{plan_advice}\n\n"
                            f"**Understanding Your Recommendation**:\n{plan_explanation}"
                        )

        elif intent in ("profile_update", "goal_update"):
            # Persist updated facts to DB, run ConsultantEngine
            new_slots = normalize_llm_output({}, user_message)
            active_profile = dict(existing_profile) if existing_profile else {}
            for k, v in new_slots.items():
                if v is not None:
                    active_profile[k] = v

            t_eng_start = time.perf_counter()
            result_dto, error_dto = AdvisorServices.consult(active_profile, lang=lang)
            consultant_engine_ms = round((time.perf_counter() - t_eng_start) * 1000.0, 2)

            if result_dto and result_dto.get("success"):
                inc_v = active_profile.get("monthly_income")
                exp_v = active_profile.get("monthly_expense")
                goal_v = active_profile.get("goal_cost")
                surplus_v = (inc_v - exp_v) if (inc_v is not None and exp_v is not None) else None

                # Store active profile and transition state in session for subsequent turns
                from flask import session as flask_session
                flask_session["prev_advisor_profile"] = dict(existing_profile) if existing_profile else {}
                flask_session["advisor_profile"] = dict(active_profile, _user_id=current_user.id)
                flask_session.modified = True

                if intent == "goal_update" and goal_v is not None:
                    ai_response = (
                        f"គោលដៅសន្សំរបស់អ្នកត្រូវបានធ្វើបច្ចុប្បន្នភាពទៅជា ${goal_v:,.0f}។ ចំណូល និងការចំណាយនៅដដែល។"
                        if lang == "km"
                        else f"Your savings goal has been updated to ${goal_v:,.0f}. Your income and expenses remain intact."
                    )
                elif inc_v is not None and exp_v is not None and surplus_v is not None:
                    ai_response = (
                        f"បានធ្វើបច្ចុប្បន្នភាពកម្រងព័ត៌មានរបស់អ្នក៖ ចំណូល ${inc_v:,.0f}/ខែ, ចំណាយ ${exp_v:,.0f}/ខែ, សល់សុទ្ធ ${surplus_v:,.0f}/ខែ។"
                        if lang == "km"
                        else f"Your profile has been updated: income ${inc_v:,.0f}/mo, expenses ${exp_v:,.0f}/mo, leaving a new monthly surplus of ${surplus_v:,.0f}/mo."
                    )
                else:
                    consultant_advice = result_dto.get("advice", {}).get(lang) or result_dto.get("advice", {}).get("en", "")

        elif intent == "change_impact_query":
            # Compare current profile with previous profile
            from flask import session as flask_session
            prev_p = flask_session.get("prev_advisor_profile")
            curr_p = flask_session.get("advisor_profile")

            if prev_p and curr_p:
                prev_inc = prev_p.get("monthly_income") or 0.0
                prev_exp = prev_p.get("monthly_expense") or 0.0
                prev_surplus = prev_inc - prev_exp

                curr_inc = curr_p.get("monthly_income") or 0.0
                curr_exp = curr_p.get("monthly_expense") or 0.0
                curr_surplus = curr_inc - curr_exp

                diff = curr_surplus - prev_surplus
                if diff > 0:
                    ai_response = (
                        f"ការផ្លាស់ប្តូរនេះបង្កើនប្រាក់សល់ប្រចាំខែរបស់អ្នកពី ${prev_surplus:,.0f} ទៅ ${curr_surplus:,.0f} (កើនឡើង ${diff:,.0f} បន្ថែមទៀតក្នុងមួយខែ)។"
                        if lang == "km"
                        else f"This change increased your monthly surplus from ${prev_surplus:,.0f} to ${curr_surplus:,.0f}, providing an additional ${diff:,.0f} each month."
                    )
                elif diff < 0:
                    diff_abs = abs(diff)
                    ai_response = (
                        f"ការផ្លាស់ប្តូរនេះបន្ថយប្រាក់សល់ប្រចាំខែរបស់អ្នកពី ${prev_surplus:,.0f} មកត្រឹម ${curr_surplus:,.0f} (ថយចុះ ${diff_abs:,.0f} ក្នុងមួយខែ) ដោយទុកឱ្យអ្នកនូវសមត្ថភាពសន្សំ ${curr_surplus:,.0f}/ខែ។"
                        if lang == "km"
                        else f"This change reduces your monthly surplus from ${prev_surplus:,.0f} to ${curr_surplus:,.0f} (a reduction of ${diff_abs:,.0f} each month), leaving you with a verified savings capacity of ${curr_surplus:,.0f}/mo."
                    )
                else:
                    ai_response = (
                        f"ប្រាក់សល់ប្រចាំខែរបស់អ្នកនៅដដែលគឺ ${curr_surplus:,.0f} ក្នុងមួយខែ។"
                        if lang == "km"
                        else f"This change does not affect your monthly surplus, which remains at ${curr_surplus:,.0f}/mo."
                    )
            else:
                histories = (
                    History.query.filter(History.users.any(id=current_user.id))
                    .order_by(History.created_at.desc(), History.id.desc())
                    .limit(2)
                    .all()
                )
                if len(histories) >= 2:
                    prev_inc = histories[1].income or 0.0
                    prev_exp = histories[1].expense or 0.0
                    prev_surplus = prev_inc - prev_exp

                    curr_inc = histories[0].income or 0.0
                    curr_exp = histories[0].expense or 0.0
                    curr_surplus = curr_inc - curr_exp

                    diff = curr_surplus - prev_surplus
                    if diff < 0:
                        diff_abs = abs(diff)
                        ai_response = (
                            f"ការផ្លាស់ប្តូរនេះបន្ថយប្រាក់សល់ប្រចាំខែរបស់អ្នកពី ${prev_surplus:,.0f} មកត្រឹម ${curr_surplus:,.0f} (ថយចុះ ${diff_abs:,.0f} ក្នុងមួយខែ)។"
                            if lang == "km"
                            else f"This change reduces your monthly surplus from ${prev_surplus:,.0f} to ${curr_surplus:,.0f} (a reduction of ${diff_abs:,.0f} each month)."
                        )
                    else:
                        ai_response = (
                            f"ការផ្លាស់ប្តូរនេះបង្កើនប្រាក់សល់ប្រចាំខែរបស់អ្នកពី ${prev_surplus:,.0f} ទៅ ${curr_surplus:,.0f} (កើនឡើង ${diff:,.0f} បន្ថែមទៀតក្នុងមួយខែ)។"
                            if lang == "km"
                            else f"This change increased your monthly surplus from ${prev_surplus:,.0f} to ${curr_surplus:,.0f}, providing an additional ${diff:,.0f} each month."
                        )

        # --- Generate response via Trained Local AI if not already resolved ---
        t_llm_start = time.perf_counter()
        chat_result = {}
        if ai_response is None:
            chat_result = LLMService.chat_interact(
                user_message,
                existing_profile=existing_profile,
                lang=lang,
                consultant_advice=consultant_advice,
            )
            ai_response = chat_result.get("response", "")
        t_llm_end = time.perf_counter()
        llm_service_ms = round((t_llm_end - t_llm_start) * 1000.0, 2)

        # Last-resort fallback only if LLM server is completely unreachable
        if not ai_response or not ai_response.strip():
            if lang == "km":
                ai_response = "ខ្ញុំជាជំនួយការប្រឹក្សាហិរញ្ញវត្ថុ AI។ សូមសួរសំណួរអំពីថវិកា ការចំណាយ ឬការសន្សំរបស់អ្នក។"
            else:
                ai_response = "I am your Financial Advisor AI. Please ask me about your budget, expenses, or savings."

        # Authoritative Output Normalizer & Sanitizer verification on all responses
        from training.llm_output_normalizer import normalize_and_verify_response
        ai_response = normalize_and_verify_response(
            ai_response,
            user_input=user_message,
            context_profile=existing_profile,
            lang=lang
        )

        # Save user message
        db.session.add(
            AIMessage(
                ai_id=ai_chat.id,
                content=user_message,
                is_ai=False
            )
        )

        # Save AI message
        db.session.add(
            AIMessage(
                ai_id=ai_chat.id,
                content=ai_response,
                is_ai=True
            )
        )

        ai_chat.counts += 2
        ai_chat.updated_at = datetime.utcnow()

        db.session.commit()

        total_chatbot_response_ms = round((time.perf_counter() - t_req_start) * 1000.0, 2)

        model_timing = chat_result.get("timing") or {}

        timing_data = {
            "intent": intent,
            "intent_classification_ms": intent_classification_ms,
            "db_profile_loading_ms": db_profile_loading_ms,
            "consultant_engine_ms": consultant_engine_ms,
            "llm_service_ms": llm_service_ms,
            "http_to_5006_ms": chat_result.get("http_to_5006_ms", 0.0),
            "model_prompt_tokenization_ms": model_timing.get("tokenization_ms", 0.0),
            "model_generation_ms": model_timing.get("generation_ms", 0.0),
            "number_of_generated_tokens": model_timing.get("output_tokens", 0),
            "input_tokens": model_timing.get("input_tokens", 0),
            "tokens_per_second": model_timing.get("tokens_per_second", 0.0),
            "total_chatbot_response_ms": total_chatbot_response_ms,
        }

        print(f"[TIMING REPORT] {user_message!r} -> Total: {total_chatbot_response_ms}ms | LLM: {llm_service_ms}ms | Gen: {model_timing.get('generation_ms')}ms | Tok/s: {model_timing.get('tokens_per_second')}")

        return jsonify({
            "response": ai_response,
            "chat_id": ai_chat.id,
            "timing": timing_data,
        })

    except Exception as e:
        db.session.rollback()

        print(
            f"[Local LLM Error]: "
            f"{type(e).__name__} - {e}"
        )

        return jsonify({
            "error": "Unable to process your request."
        }), 500



@bot_bp.route("/chat/current", methods=["GET"])
@login_required
def current_chat():
    try:
        # Get the user's most recently updated conversation
        ai_chat = (
            AIChat.query
            .filter(AIChat.users.any(id=current_user.id))
            .order_by(AIChat.updated_at.desc())
            .first()
        )

        if not ai_chat:
            return jsonify({
                "chat_id": None,
                "messages": []
            })

        messages = (
            AIMessage.query
            .filter_by(ai_id=ai_chat.id)
            .order_by(AIMessage.created_at.asc())
            .all()
        )

        return jsonify({
            "chat_id": ai_chat.id,
            "messages": [
                {
                    "content": message.content,
                    "is_ai": message.is_ai,
                    "created_at": (
                        message.created_at.isoformat()
                        if message.created_at
                        else None
                    )
                }
                for message in messages
            ]
        })

    except Exception as e:
        print(
            f"[Chat History Error]: "
            f"{type(e).__name__} - {e}"
        )

        return jsonify({
            "error": "Unable to load conversation."
        }), 500



@bot_bp.route("/chat/<int:chat_id>", methods=["DELETE"])
@login_required
def delete_chat(chat_id):
    try:
        ai_chat = (
            AIChat.query
            .filter(
                AIChat.id == chat_id,
                AIChat.users.any(id=current_user.id)
            )
            .first()
        )

        if not ai_chat:
            return jsonify({
                "error": "Conversation not found."
            }), 404

        db.session.delete(ai_chat)
        db.session.commit()

        return jsonify({
            "success": True
        })

    except Exception as e:
        db.session.rollback()

        print(
            f"[Delete Chat Error]: "
            f"{type(e).__name__} - {e}"
        )

        return jsonify({
            "error": "Unable to delete conversation."
        }), 500


    
@bot_bp.route('/analyse', methods=['POST'])
@login_required
@limiter.limit("15 per minute; 60 per hour")
def analyse():
    try:
        data = request.get_json(silent=True) or {}
        user_message = data.get('message', '').strip()

        if not user_message:
            return jsonify({'error': 'Message cannot be empty'}), 400

        chat_result = LLMService.chat_interact(user_message)
        ai_response = chat_result.get('response', 'I can only assist with finance, budgeting, tax, and investment inquiries.')
        return jsonify({'response': ai_response})

    except Exception as e:
        print(f"[Local LLM Error]: {type(e).__name__} - {e}")
        return jsonify({'error': 'Backend error during financial analysis.'}), 500